name = "good-luck-island"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[analytics_engine_datasets]]
binding = "AnalyticsEngineDataset"
dataset = "good_luck_island_events"
