// Hand-maintained D1 type source. Originally generated by the Supabase CLI
// before this app's Postgres -> Cloudflare D1 cutover; kept in this shape
// (Database/Tables/TablesInsert/TablesUpdate) since it was already the
// established convention here, but simplified to a single flat schema --
// D1 has no multi-schema/RLS/RPC concept, so the old
// graphql_public/__InternalSupabase/Functions/Enums scaffolding is gone.
// Update this file by hand alongside each new migration in goodLuckAdmin's
// migrations/*.sql (that repo owns the schema; this is just the D1 type
// mirror consumed here).
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  Tables: {
      admins: {
        Row: {
          created_at: string;
          id: string;
        };
        Insert: {
          created_at?: string;
          id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          body: string;
          read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          body: string;
          read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          body?: string;
          read?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      saved_items: {
        Row: {
          id: string;
          user_id: string;
          item_type: string;
          item_id: number;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          item_type: string;
          item_id: number;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          item_type?: string;
          item_id?: number;
          created_at?: string | null;
        };
        Relationships: [];
      };
      articles: {
        Row: {
          category: string;
          created_at: string | null;
          date: string | null;
          excerpt: string | null;
          featured: boolean;
          id: number;
          image: string | null;
          read_time: string | null;
          sort_order: number;
          title: string;
        };
        Insert: {
          category?: string;
          created_at?: string | null;
          date?: string | null;
          excerpt?: string | null;
          featured?: boolean;
          id?: number;
          image?: string | null;
          read_time?: string | null;
          sort_order?: number;
          title: string;
        };
        Update: {
          category?: string;
          created_at?: string | null;
          date?: string | null;
          excerpt?: string | null;
          featured?: boolean;
          id?: number;
          image?: string | null;
          read_time?: string | null;
          sort_order?: number;
          title?: string;
        };
        Relationships: [];
      };
      backpack_sections: {
        Row: {
          color: string;
          description: string;
          emoji: string;
          id: string;
          label: string;
          slug: string;
          sort_order: number;
          tagline: string;
          type: string;
        };
        Insert: {
          color?: string;
          description?: string;
          emoji?: string;
          id?: string;
          label: string;
          slug: string;
          sort_order?: number;
          tagline?: string;
          type?: string;
        };
        Update: {
          color?: string;
          description?: string;
          emoji?: string;
          id?: string;
          label?: string;
          slug?: string;
          sort_order?: number;
          tagline?: string;
          type?: string;
        };
        Relationships: [];
      };
      pinwirl_answers: {
        Row: {
          id: string;
          user_id: string;
          question_id: string | null;
          answer: string;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          question_id?: string | null;
          answer?: string;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          question_id?: string | null;
          answer?: string;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "pinwirl_answers_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "pinwirl_questions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "pinwirl_answers_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      pinwirl_answer_options: {
        Row: {
          created_at: string;
          id: string;
          option_text: string;
          order_index: number;
          question_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          option_text: string;
          order_index: number;
          question_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          option_text?: string;
          order_index?: number;
          question_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "pinwirl_answer_options_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "pinwirl_questions";
            referencedColumns: ["id"];
          },
        ];
      };
      pinwirl_questions: {
        Row: {
          created_at: string;
          external_id: string;
          hint: string | null;
          id: string;
          order_index: number;
          question_text: string;
          question_type: "scale" | "narrative" | "radio" | "select" | "number" | "text";
          required: boolean;
          scale_max: string | null;
          scale_min: string | null;
          section: string;
        };
        Insert: {
          created_at?: string;
          external_id: string;
          hint?: string | null;
          id?: string;
          order_index: number;
          question_text: string;
          question_type: "scale" | "narrative" | "radio" | "select" | "number" | "text";
          required?: boolean;
          scale_max?: string | null;
          scale_min?: string | null;
          section: string;
        };
        Update: {
          created_at?: string;
          external_id?: string;
          hint?: string | null;
          id?: string;
          order_index?: number;
          question_text?: string;
          question_type?: "scale" | "narrative" | "radio" | "select" | "number" | "text";
          required?: boolean;
          scale_max?: string | null;
          scale_min?: string | null;
          section?: string;
        };
        Relationships: [];
      };
      one_question_answer_options: {
        Row: {
          created_at: string | null;
          id: string;
          option_text: string;
          order_index: number;
          question_id: string;
        };
        Insert: {
          created_at?: string | null;
          id?: string;
          option_text: string;
          order_index: number;
          question_id: string;
        };
        Update: {
          created_at?: string | null;
          id?: string;
          option_text?: string;
          order_index?: number;
          question_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "one_question_answer_options_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "one_questions";
            referencedColumns: ["id"];
          },
        ];
      };
      pinwirl_recommendations: {
        Row: {
          id: string;
          dimension: string;
          band: string;
          body: string;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          dimension: string;
          band: string;
          body: string;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          dimension?: string;
          band?: string;
          body?: string;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      pinwirl_results: {
        Row: {
          id: string;
          user_id: string;
          taken_at: string;
          scores: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          taken_at?: string;
          scores: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          taken_at?: string;
          scores?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      one_questions: {
        Row: {
          content: string;
          created_at: string;
          hint: string | null;
          id: string;
          index: number | null;
          question_type: "scale" | "radio" | "select" | "number" | "text";
          required: boolean;
          scale_max: string | null;
          scale_min: string | null;
        };
        Insert: {
          content?: string;
          created_at?: string;
          hint?: string | null;
          id?: string;
          index?: number | null;
          question_type?: "scale" | "radio" | "select" | "number" | "text";
          required?: boolean;
          scale_max?: string | null;
          scale_min?: string | null;
        };
        Update: {
          content?: string;
          created_at?: string;
          hint?: string | null;
          id?: string;
          index?: number | null;
          question_type?: "scale" | "radio" | "select" | "number" | "text";
          required?: boolean;
          scale_max?: string | null;
          scale_min?: string | null;
        };
        Relationships: [];
      };
      one_question_answers: {
        Row: {
          answer: string;
          created_at: string | null;
          id: string;
          question_id: string | null;
          question_index: number;
          updated_at: string | null;
          user_id: string;
        };
        Insert: {
          answer?: string;
          created_at?: string | null;
          id?: string;
          question_id?: string | null;
          question_index: number;
          updated_at?: string | null;
          user_id: string;
        };
        Update: {
          answer?: string;
          created_at?: string | null;
          id?: string;
          question_id?: string | null;
          question_index?: number;
          updated_at?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "one_question_answers_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "one_questions";
            referencedColumns: ["id"];
          },
        ];
      };
      journal_entries: {
        Row: {
          id: string;
          user_id: string;
          step_slug: string;
          body: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          step_slug: string;
          body?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          step_slug?: string;
          body?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      past_person_answers: {
        Row: {
          id: string;
          user_id: string;
          question_key: string;
          answer: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          question_key: string;
          answer?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          question_key?: string;
          answer?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      past_person_questions: {
        Row: {
          id: string;
          key: string;
          text: string;
          placeholder: string;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          text: string;
          placeholder?: string;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          text?: string;
          placeholder?: string;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      reflections: {
        Row: {
          id: string;
          step_slug: string;
          body: string;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          step_slug: string;
          body: string;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          step_slug?: string;
          body?: string;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      users_seven_step_process: {
        Row: {
          id: number;
          user_id: string;
          one_question_challenge: boolean;
          wayfair_tool: boolean;
          values_and_beliefs: boolean;
          finding_your_purpose: boolean;
          new_skills: boolean;
          retirement: boolean;
          give_back_step: boolean;
        };
        Insert: {
          id?: number;
          user_id: string;
          one_question_challenge?: boolean;
          wayfair_tool?: boolean;
          values_and_beliefs?: boolean;
          finding_your_purpose?: boolean;
          new_skills?: boolean;
          retirement?: boolean;
          give_back_step?: boolean;
        };
        Update: {
          id?: number;
          user_id?: string;
          one_question_challenge?: boolean;
          wayfair_tool?: boolean;
          values_and_beliefs?: boolean;
          finding_your_purpose?: boolean;
          new_skills?: boolean;
          retirement?: boolean;
          give_back_step?: boolean;
        };
        Relationships: [];
      };
      episodes: {
        Row: {
          created_at: string | null;
          date: string | null;
          description: string | null;
          duration: string | null;
          id: number;
          num: string;
          sort_order: number;
          thumbnail: string | null;
          title: string;
          youtube_id: string | null;
        };
        Insert: {
          created_at?: string | null;
          date?: string | null;
          description?: string | null;
          duration?: string | null;
          id?: number;
          num: string;
          sort_order?: number;
          thumbnail?: string | null;
          title: string;
          youtube_id?: string | null;
        };
        Update: {
          created_at?: string | null;
          date?: string | null;
          description?: string | null;
          duration?: string | null;
          id?: number;
          num?: string;
          sort_order?: number;
          thumbnail?: string | null;
          title?: string;
          youtube_id?: string | null;
        };
        Relationships: [];
      };
      users: {
        Row: {
          age: number | null;
          avatar_id: string | null;
          bio: string | null;
          blocked_at: string | null;
          created_at: string | null;
          divorced: string | null;
          education: string | null;
          email: string;
          first_name: string | null;
          home_paid_off: string | null;
          id: string;
          interests: string[] | null;
          is_deleted: boolean;
          kids: string | null;
          last_login: string | null;
          last_name: string | null;
          location: string | null;
          mantra: string | null;
          marital_status: string | null;
          net_worth: string | null;
          notifications_email: boolean;
          occupation: string | null;
          retired: string | null;
          retirement_date: string | null;
          unsubscribed_at: string | null;
          updated_at: string | null;
          username: string | null;
          working_income: string | null;
          years_in_occupation: number | null;
        };
        Insert: {
          age?: number | null;
          avatar_id?: string | null;
          bio?: string | null;
          created_at?: string | null;
          divorced?: string | null;
          education?: string | null;
          email: string;
          first_name?: string | null;
          home_paid_off?: string | null;
          id: string;
          interests?: string[] | null;
          is_deleted?: boolean;
          kids?: string | null;
          last_login?: string | null;
          last_name?: string | null;
          location?: string | null;
          mantra?: string | null;
          marital_status?: string | null;
          net_worth?: string | null;
          notifications_email?: boolean;
          occupation?: string | null;
          retired?: string | null;
          retirement_date?: string | null;
          unsubscribed_at?: string | null;
          updated_at?: string | null;
          username?: string | null;
          working_income?: string | null;
          years_in_occupation?: number | null;
        };
        Update: {
          age?: number | null;
          avatar_id?: string | null;
          bio?: string | null;
          created_at?: string | null;
          divorced?: string | null;
          education?: string | null;
          email?: string;
          first_name?: string | null;
          home_paid_off?: string | null;
          id?: string;
          interests?: string[] | null;
          is_deleted?: boolean;
          kids?: string | null;
          last_login?: string | null;
          last_name?: string | null;
          location?: string | null;
          mantra?: string | null;
          marital_status?: string | null;
          net_worth?: string | null;
          notifications_email?: boolean;
          occupation?: string | null;
          retired?: string | null;
          retirement_date?: string | null;
          unsubscribed_at?: string | null;
          updated_at?: string | null;
          username?: string | null;
          working_income?: string | null;
          years_in_occupation?: number | null;
        };
        Relationships: [];
      };
    };
};

// D1 has one flat schema (no multi-schema/RLS concept like Postgres), so
// these no longer need the schema-option overload the Supabase CLI
// generates -- just index straight into Database["Tables"].
export type Tables<TableName extends keyof Database["Tables"]> =
  Database["Tables"][TableName]["Row"];

export type TablesInsert<TableName extends keyof Database["Tables"]> =
  Database["Tables"][TableName]["Insert"];

export type TablesUpdate<TableName extends keyof Database["Tables"]> =
  Database["Tables"][TableName]["Update"];

