// Generated by Supabase CLI — partially hand-edited.
// one_question_answer_options table and one_questions new columns (question_type,
// hint, required, scale_min, scale_max) were added manually and must be re-applied
// after any `supabase gen types typescript > src/types/supabase.ts` run.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4";
  };
  graphql_public: {
    Tables: {
      [_ in never]: never;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      graphql: {
        Args: {
          extensions?: Json;
          operationName?: string;
          query?: string;
          variables?: Json;
        };
        Returns: Json;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  public: {
    Tables: {
      admins: {
        Row: {
          created_at: string;
          id: string;
        };
        Insert: {
          created_at?: string;
          id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          body: string;
          read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          body: string;
          read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          body?: string;
          read?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      saved_items: {
        Row: {
          id: string;
          user_id: string;
          item_type: string;
          item_id: number;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          item_type: string;
          item_id: number;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          item_type?: string;
          item_id?: number;
          created_at?: string | null;
        };
        Relationships: [];
      };
      articles: {
        Row: {
          category: string;
          created_at: string | null;
          date: string | null;
          excerpt: string | null;
          featured: boolean;
          id: number;
          image: string | null;
          read_time: string | null;
          sort_order: number;
          title: string;
        };
        Insert: {
          category?: string;
          created_at?: string | null;
          date?: string | null;
          excerpt?: string | null;
          featured?: boolean;
          id?: number;
          image?: string | null;
          read_time?: string | null;
          sort_order?: number;
          title: string;
        };
        Update: {
          category?: string;
          created_at?: string | null;
          date?: string | null;
          excerpt?: string | null;
          featured?: boolean;
          id?: number;
          image?: string | null;
          read_time?: string | null;
          sort_order?: number;
          title?: string;
        };
        Relationships: [];
      };
      backpack_sections: {
        Row: {
          color: string;
          description: string;
          emoji: string;
          id: string;
          label: string;
          slug: string;
          sort_order: number;
          tagline: string;
          type: string;
        };
        Insert: {
          color?: string;
          description?: string;
          emoji?: string;
          id?: string;
          label: string;
          slug: string;
          sort_order?: number;
          tagline?: string;
          type?: string;
        };
        Update: {
          color?: string;
          description?: string;
          emoji?: string;
          id?: string;
          label?: string;
          slug?: string;
          sort_order?: number;
          tagline?: string;
          type?: string;
        };
        Relationships: [];
      };
      pinwirl_answers: {
        Row: {
          id: string;
          user_id: string;
          question_id: string | null;
          answer: string;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          question_id?: string | null;
          answer?: string;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          question_id?: string | null;
          answer?: string;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "pinwirl_answers_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "pinwirl_questions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "pinwirl_answers_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      pinwirl_answer_options: {
        Row: {
          created_at: string;
          id: string;
          option_text: string;
          order_index: number;
          question_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          option_text: string;
          order_index: number;
          question_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          option_text?: string;
          order_index?: number;
          question_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "pinwirl_answer_options_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "pinwirl_questions";
            referencedColumns: ["id"];
          },
        ];
      };
      pinwirl_questions: {
        Row: {
          created_at: string;
          external_id: string;
          hint: string | null;
          id: string;
          order_index: number;
          question_text: string;
          question_type: "scale" | "narrative" | "radio" | "select" | "number" | "text";
          required: boolean;
          scale_max: string | null;
          scale_min: string | null;
          section: string;
        };
        Insert: {
          created_at?: string;
          external_id: string;
          hint?: string | null;
          id?: string;
          order_index: number;
          question_text: string;
          question_type: "scale" | "narrative" | "radio" | "select" | "number" | "text";
          required?: boolean;
          scale_max?: string | null;
          scale_min?: string | null;
          section: string;
        };
        Update: {
          created_at?: string;
          external_id?: string;
          hint?: string | null;
          id?: string;
          order_index?: number;
          question_text?: string;
          question_type?: "scale" | "narrative" | "radio" | "select" | "number" | "text";
          required?: boolean;
          scale_max?: string | null;
          scale_min?: string | null;
          section?: string;
        };
        Relationships: [];
      };
      one_question_answer_options: {
        Row: {
          created_at: string | null;
          id: string;
          option_text: string;
          order_index: number;
          question_id: string;
        };
        Insert: {
          created_at?: string | null;
          id?: string;
          option_text: string;
          order_index: number;
          question_id: string;
        };
        Update: {
          created_at?: string | null;
          id?: string;
          option_text?: string;
          order_index?: number;
          question_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "one_question_answer_options_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "one_questions";
            referencedColumns: ["id"];
          },
        ];
      };
      pinwirl_recommendations: {
        Row: {
          id: string;
          dimension: string;
          band: string;
          body: string;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          dimension: string;
          band: string;
          body: string;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          dimension?: string;
          band?: string;
          body?: string;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      pinwirl_results: {
        Row: {
          id: string;
          user_id: string;
          taken_at: string;
          scores: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          taken_at?: string;
          scores: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          taken_at?: string;
          scores?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      one_questions: {
        Row: {
          content: string;
          created_at: string;
          hint: string | null;
          id: string;
          index: number | null;
          question_type: "scale" | "radio" | "select" | "number" | "text";
          required: boolean;
          scale_max: string | null;
          scale_min: string | null;
        };
        Insert: {
          content?: string;
          created_at?: string;
          hint?: string | null;
          id?: string;
          index?: number | null;
          question_type?: "scale" | "radio" | "select" | "number" | "text";
          required?: boolean;
          scale_max?: string | null;
          scale_min?: string | null;
        };
        Update: {
          content?: string;
          created_at?: string;
          hint?: string | null;
          id?: string;
          index?: number | null;
          question_type?: "scale" | "radio" | "select" | "number" | "text";
          required?: boolean;
          scale_max?: string | null;
          scale_min?: string | null;
        };
        Relationships: [];
      };
      one_question_answers: {
        Row: {
          answer: string;
          created_at: string | null;
          id: string;
          question_id: string | null;
          question_index: number;
          updated_at: string | null;
          user_id: string;
        };
        Insert: {
          answer?: string;
          created_at?: string | null;
          id?: string;
          question_id?: string | null;
          question_index: number;
          updated_at?: string | null;
          user_id: string;
        };
        Update: {
          answer?: string;
          created_at?: string | null;
          id?: string;
          question_id?: string | null;
          question_index?: number;
          updated_at?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "one_question_answers_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "one_questions";
            referencedColumns: ["id"];
          },
        ];
      };
      journal_entries: {
        Row: {
          id: string;
          user_id: string;
          step_slug: string;
          body: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          step_slug: string;
          body?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          step_slug?: string;
          body?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      past_person_answers: {
        Row: {
          id: string;
          user_id: string;
          question_key: string;
          answer: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          question_key: string;
          answer?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          question_key?: string;
          answer?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      past_person_questions: {
        Row: {
          id: string;
          key: string;
          text: string;
          placeholder: string;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          text: string;
          placeholder?: string;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          text?: string;
          placeholder?: string;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      reflections: {
        Row: {
          id: string;
          step_slug: string;
          body: string;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          step_slug: string;
          body: string;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          step_slug?: string;
          body?: string;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      users_seven_step_process: {
        Row: {
          id: number;
          user_id: string;
          one_question_challenge: boolean;
          wayfair_tool: boolean;
          values_and_beliefs: boolean;
          finding_your_purpose: boolean;
          new_skills: boolean;
          retirement: boolean;
          give_back_step: boolean;
        };
        Insert: {
          id?: number;
          user_id: string;
          one_question_challenge?: boolean;
          wayfair_tool?: boolean;
          values_and_beliefs?: boolean;
          finding_your_purpose?: boolean;
          new_skills?: boolean;
          retirement?: boolean;
          give_back_step?: boolean;
        };
        Update: {
          id?: number;
          user_id?: string;
          one_question_challenge?: boolean;
          wayfair_tool?: boolean;
          values_and_beliefs?: boolean;
          finding_your_purpose?: boolean;
          new_skills?: boolean;
          retirement?: boolean;
          give_back_step?: boolean;
        };
        Relationships: [];
      };
      episodes: {
        Row: {
          created_at: string | null;
          date: string | null;
          description: string | null;
          duration: string | null;
          id: number;
          num: string;
          sort_order: number;
          thumbnail: string | null;
          title: string;
          youtube_id: string | null;
        };
        Insert: {
          created_at?: string | null;
          date?: string | null;
          description?: string | null;
          duration?: string | null;
          id?: number;
          num: string;
          sort_order?: number;
          thumbnail?: string | null;
          title: string;
          youtube_id?: string | null;
        };
        Update: {
          created_at?: string | null;
          date?: string | null;
          description?: string | null;
          duration?: string | null;
          id?: number;
          num?: string;
          sort_order?: number;
          thumbnail?: string | null;
          title?: string;
          youtube_id?: string | null;
        };
        Relationships: [];
      };
      users: {
        Row: {
          age: number | null;
          avatar_id: string | null;
          bio: string | null;
          blocked_at: string | null;
          city: string | null;
          created_at: string | null;
          divorced: string | null;
          education: string | null;
          email: string;
          employment_status: string | null;
          first_name: string | null;
          gender: string | null;
          geo_classifier: string | null;
          home_paid_off: string | null;
          household_composition: string | null;
          id: string;
          ideal_retirement_day: string | null;
          industry: string | null;
          interests: string[] | null;
          is_deleted: boolean;
          kids: string | null;
          last_login: string | null;
          last_name: string | null;
          life_satisfaction: number | null;
          location: string | null;
          loneliness_connection: number | null;
          mantra: string | null;
          marital_status: string | null;
          net_worth: string | null;
          notifications_email: boolean;
          notifications_in_app: boolean;
          occupation: string | null;
          optimism: number | null;
          retired: string | null;
          retirement_concerns: string[] | null;
          retirement_confidence: number | null;
          retirement_date: string | null;
          retirement_date_reason: string | null;
          retirement_identity: string | null;
          retirement_motivations: string[] | null;
          retirement_vision_clarity: number | null;
          sense_of_purpose: number | null;
          state: string | null;
          stress_level: number | null;
          unsubscribed_at: string | null;
          updated_at: string | null;
          username: string | null;
          working_income: string | null;
          years_in_occupation: number | null;
          years_until_retirement: string | null;
          zip_code: string | null;
        };
        Insert: {
          age?: number | null;
          avatar_id?: string | null;
          bio?: string | null;
          city?: string | null;
          created_at?: string | null;
          divorced?: string | null;
          education?: string | null;
          email: string;
          employment_status?: string | null;
          first_name?: string | null;
          gender?: string | null;
          geo_classifier?: string | null;
          home_paid_off?: string | null;
          household_composition?: string | null;
          id: string;
          ideal_retirement_day?: string | null;
          industry?: string | null;
          interests?: string[] | null;
          is_deleted?: boolean;
          kids?: string | null;
          last_login?: string | null;
          last_name?: string | null;
          life_satisfaction?: number | null;
          location?: string | null;
          loneliness_connection?: number | null;
          mantra?: string | null;
          marital_status?: string | null;
          net_worth?: string | null;
          notifications_email?: boolean;
          notifications_in_app?: boolean;
          occupation?: string | null;
          optimism?: number | null;
          retired?: string | null;
          retirement_concerns?: string[] | null;
          retirement_confidence?: number | null;
          retirement_date?: string | null;
          retirement_date_reason?: string | null;
          retirement_identity?: string | null;
          retirement_motivations?: string[] | null;
          retirement_vision_clarity?: number | null;
          sense_of_purpose?: number | null;
          state?: string | null;
          stress_level?: number | null;
          unsubscribed_at?: string | null;
          updated_at?: string | null;
          username?: string | null;
          working_income?: string | null;
          years_in_occupation?: number | null;
          years_until_retirement?: string | null;
          zip_code?: string | null;
        };
        Update: {
          age?: number | null;
          avatar_id?: string | null;
          bio?: string | null;
          city?: string | null;
          created_at?: string | null;
          divorced?: string | null;
          education?: string | null;
          email?: string;
          employment_status?: string | null;
          first_name?: string | null;
          gender?: string | null;
          geo_classifier?: string | null;
          home_paid_off?: string | null;
          household_composition?: string | null;
          id?: string;
          ideal_retirement_day?: string | null;
          industry?: string | null;
          interests?: string[] | null;
          is_deleted?: boolean;
          kids?: string | null;
          last_login?: string | null;
          last_name?: string | null;
          life_satisfaction?: number | null;
          location?: string | null;
          loneliness_connection?: number | null;
          mantra?: string | null;
          marital_status?: string | null;
          net_worth?: string | null;
          notifications_email?: boolean;
          notifications_in_app?: boolean;
          occupation?: string | null;
          optimism?: number | null;
          retired?: string | null;
          retirement_concerns?: string[] | null;
          retirement_confidence?: number | null;
          retirement_date?: string | null;
          retirement_date_reason?: string | null;
          retirement_identity?: string | null;
          retirement_motivations?: string[] | null;
          retirement_vision_clarity?: number | null;
          sense_of_purpose?: number | null;
          state?: string | null;
          stress_level?: number | null;
          unsubscribed_at?: string | null;
          updated_at?: string | null;
          username?: string | null;
          working_income?: string | null;
          years_in_occupation?: number | null;
          years_until_retirement?: string | null;
          zip_code?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      admin_age_distribution: {
        Args: never;
        Returns: {
          count: number;
          label: string;
        }[];
      };
      admin_field_distribution: {
        Args: { p_field: string };
        Returns: {
          count: number;
          label: string;
        }[];
      };
      admin_location_distribution: {
        Args: never;
        Returns: {
          city: string;
          count: number;
        }[];
      };
      admin_overview_stats: { Args: never; Returns: Json };
      admin_signup_trend: {
        Args: never;
        Returns: {
          count: number;
          month: string;
        }[];
      };
      is_admin: { Args: { user_id: string }; Returns: boolean };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const;
